<a href="https://colab.research.google.com/github/kalakhushi18/CNN-/blob/main/Tensors_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [3]:
data = torch.tensor([1,2], dtype= torch.float32)  #list of items
print(data)

tensor([1., 2.])


In [5]:
zeroes = torch.zeros(1,5)
zeroes

tensor([[0., 0., 0., 0., 0.]])

In [7]:
ones = torch.ones(2,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [8]:
ones.shape

torch.Size([2, 5])

In [9]:
r = torch.arange(1,6) #similar to range in arrays
r

tensor([1, 2, 3, 4, 5])

In [10]:
print(r+2)
print(r*2)

tensor([3, 4, 5, 6, 7])
tensor([ 2,  4,  6,  8, 10])


In [14]:
a = torch.tensor([[1,2], [3,4], [5,6]]) # 3x2
b= torch.tensor([[1,2,3,4], [5,6,1,8]]) # 2x4

print("Mul is : ", a.matmul(b)) #3x4
print("Withh operand:", a @ b)

Mul is :  tensor([[11, 14,  5, 20],
        [23, 30, 13, 44],
        [35, 46, 21, 68]])
Withh operand: tensor([[11, 14,  5, 20],
        [23, 30, 13, 44],
        [35, 46, 21, 68]])


Pytorch can reshape the tensors for certain operations execution, so if you get the error in pytorch it could be different, but you have to make sure to check each time the shape when you perform a matrix operation, because shapes in tensor usually throws error.

In [ ]:
#printing shape of all tensors is the main idea behind debugging

Why reshaping is imp?
When you will have a long list of data you need to work with it in batches and thus you need to reshape the tensors to work in batches, or sequences of sentenses

In [15]:
demo = torch.arange(1,10)
demo.shape

torch.Size([9])

In [19]:
#reshping
demo.reshape((3,3))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
oper_t = torch.arange(1,7).reshape(3,2)
print("Tensor:", oper_t)
sum_oper = oper_t.sum(dim= 0) #summing is collapsing or reducing the size of tensor
print("sum:", sum_oper)

Tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])
sum: tensor([ 9, 12])


Indexing: You can slice the tensor in multiplt different ways and get different tensors out of it, make sure of the shape.

Autograd:
It is actually storing all the nodes in gradients in forward and then in the backend the pytorch uses all these gradients to perform the chain rule in back propagation for optimizer.
By default the gradient is stored is true. It accumulates the gradient. This is for computing the loss accorss our neural network.

In [30]:
x = torch.tensor([2], requires_grad=True, dtype = torch.float32)
print(x.grad)

None


In [32]:
z = x *x * 3
z.backward()
print(x.grad)

# it accumulates every time

tensor([24.])


In [35]:
input = torch.tensor([2,3], dtype = torch.float32)

linear = nn.Linear(2,1)

linear_output = linear(input)
linear_output

tensor([-1.7787], grad_fn=<ViewBackward0>)

In [38]:
list(linear.parameters())

# weight and bias, current values which will change as we train the neural network

[Parameter containing:
 tensor([[ 0.0456, -0.4741]], requires_grad=True),
 Parameter containing:
 tensor([-0.4477], requires_grad=True)]

In [39]:
block = nn.Sequential(nn.Linear(2,1), nn.Sigmoid() )
# input layer and output layer define
input = torch.ones(1,2)
output = block(input)
output


tensor([[0.4006]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Multilayer Perceptron

In [40]:
import torch.optim as optim
# importing the optimizer